"""NoteForge 本地 ``.env`` 配置的读取与安全写入。"""

from collections.abc import Mapping
import json
import os
from pathlib import Path
import tempfile


LLM_ENV_PREFIX = "NOTEFORGE_LLM_"
DEFAULT_ENV_PATH = Path(".env")


def read_dotenv(path: str | Path = DEFAULT_ENV_PATH) -> dict[str, str]:
    """读取简单 dotenv 文件；忽略注释、空行和无法解析的行。"""

    env_path = Path(path)
    try:
        lines = env_path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        return {}
    except OSError:
        return {}

    values: dict[str, str] = {}
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        value = raw_value.strip()
        if value.startswith('"') and value.endswith('"'):
            try:
                decoded = json.loads(value)
            except (json.JSONDecodeError, TypeError):
                continue
            if isinstance(decoded, str):
                value = decoded
        elif value.startswith("'") and value.endswith("'"):
            value = value[1:-1]
        values[key] = value
    return values


def merged_environment(
    environ: Mapping[str, str] | None = None,
    *,
    dotenv_path: str | Path = DEFAULT_ENV_PATH,
) -> dict[str, str]:
    """合并 ``.env`` 与环境变量，显式环境变量优先。"""

    process_values = os.environ if environ is None else environ
    return {**read_dotenv(dotenv_path), **process_values}


def write_llm_dotenv(
    values: Mapping[str, str],
    path: str | Path = DEFAULT_ENV_PATH,
) -> Path:
    """更新 dotenv 中的 NoteForge LLM 配置并保留其他内容。"""

    env_path = Path(path)
    try:
        existing_lines = env_path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        existing_lines = []

    retained_lines = [
        line
        for line in existing_lines
        if not line.lstrip().startswith(LLM_ENV_PREFIX)
    ]
    while retained_lines and not retained_lines[-1].strip():
        retained_lines.pop()

    configured_lines = [
        "# NoteForge LLM configuration (generated by `noteforge configure`)",
        *(
            f"{key}={json.dumps(value, ensure_ascii=False)}"
            for key, value in values.items()
            if key.startswith(LLM_ENV_PREFIX) and value
        ),
    ]
    output_lines = retained_lines + ([""] if retained_lines else []) + configured_lines
    content = "\n".join(output_lines) + "\n"

    env_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=env_path.parent,
            prefix=f".{env_path.name}.",
            delete=False,
        ) as temporary_file:
            temporary_file.write(content)
            temporary_path = Path(temporary_file.name)
        temporary_path.chmod(0o600)
        temporary_path.replace(env_path)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()
    return env_path
